language: python
sudo: false
cache:
  - pip

dist: xenial

before_install:
  - set -e

install:
  - bash .install_deps
  - pip install codecov

script:
  - pytest --cov=samlauthenticator --cov-report term-missing

after_success:
  - codecov

matrix:
  fast_finish: true
  include:
  - name: "Python 3.7 Oldest Dependencies"
    python: "3.7"
    env: DEPS_VERSION=OLD
  - name: "Python Nightly Latest Dependencies"
    python: nightly
    env: DEPS_VERSION=NEW
  - name: "Python Nightly Oldest Dependencies"
    python: nightly
    env: DEPS_VERSION=OLD
  - name: "Python 3.6 Latest Dependencies"
    python: "3.6"
    env: DEPS_VERSION=NEW
  - name: "Python 3.6 Oldest Dependencies"
    python: "3.6"
    env: DEPS_VERSION=OLD
  - name: "Python 3.7 Latest Dependencies"
    python: "3.7"
    env: DEPS_VERSION=NEW
